---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: debian-7.4
    run_list:
      - recipe[apt]
  - name: centos-6.4

suites:
  - name: nginx-mysql
    run_list: ['rt4_service_test::nginx_mysql']
  - name: nginx-postgresql
    run_list: ['rt4_service_test::nginx_postgresql']
  - name: apache-mysql
    run_list: ['rt4_service_test::apache_mysql']
  - name: apache-postgresql
    run_list: ['rt4_service_test::apache_postgresql']
