name 'rt4'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2'
description 'Installs/Configures request-tracker4'
long_description 'Installs/Configures request-tracker4'
version '0.0.1'

depends 'apt'
depends 'mysql', '~>5.6.1'
depends 'postgresql'
depends 'nginx'
depends 'httpd'
depends 'perl'
